from tensorflow.keras.layers import Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Dropout
from tensorflow.keras.models import Model, load_model
from tensorflow.keras import regularizers

regularizationConst_l1 = 0.0005
regularizationConst_l2 = 0.0005

def deepNN(n_inputFeatures):

    X_input = Input(shape=(n_inputFeatures,))
    X = BatchNormalization(axis = -1)(X_input)
    X = Dense(n_inputFeatures, activation='relu', 
    kernel_regularizer=regularizers.l1_l2(l1=3e-5, l2=4e-4),
    bias_regularizer=regularizers.l2(5e-4),
    activity_regularizer=regularizers.l2(1e-5))(X)
    
    # X = BatchNormalization(axis = -1)(X)
    # X = Dense(n_inputFeatures*5, activation='relu')(X)
    # X = BatchNormalization(axis = -1)(X)
    # X = Dense(n_inputFeatures*3, activation='relu')(X)
    # X = BatchNormalization(axis = -1)(X)
    # X = Dense(n_inputFeatures*2, activation='relu')(X)
    # X = BatchNormalization(axis = -1)(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-3))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-3))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-3))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-3))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-3))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-3))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-3))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-3))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-3))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-3))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-3))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-7))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-7))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-7))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-7))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-7))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-7))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-7))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-7))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-7))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-7))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-7))(X)
    #X = BatchNormalization(axis = -1)(X)
    # X = Dense(n_inputFeatures, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(n_inputFeatures, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(n_inputFeatures, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(n_inputFeatures, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(n_inputFeatures, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(n_inputFeatures, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(n_inputFeatures, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(n_inputFeatures, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    #X = BatchNormalization(axis = -1)(X)
    size = 1024
    dropoutRate = 0.3
    X = Dense(size, activation='relu', kernel_regularizer=regularizers.l1_l2(l1=3e-5, l2=9e-4), bias_regularizer=regularizers.l2(9e-4), activity_regularizer=regularizers.l2(2e-5))(X)
    X = Dropout(dropoutRate, input_shape = (size,))(X)
    X = Dense(size, activation='relu', kernel_regularizer=regularizers.l1_l2(l1=3e-5, l2=9e-4), bias_regularizer=regularizers.l2(9e-4), activity_regularizer=regularizers.l2(2e-5))(X)
    X = Dropout(dropoutRate, input_shape = (size,))(X)
    X = Dense(size, activation='relu', kernel_regularizer=regularizers.l1_l2(l1=3e-5, l2=9e-4), bias_regularizer=regularizers.l2(9e-4), activity_regularizer=regularizers.l2(2e-5))(X)
    X = Dropout(dropoutRate, input_shape = (size,))(X)
    # X = Dense(size, activation='relu', kernel_regularizer=regularizers.l1_l2(l1=1e-5, l2=5e-4), bias_regularizer=regularizers.l2(5e-4), activity_regularizer=regularizers.l2(1e-5))(X)
    # X = Dropout(dropoutRate, input_shape = (size,))(X)
    # X = Dense(size, activation='relu', kernel_regularizer=regularizers.l1_l2(l1=1e-5, l2=5e-4), bias_regularizer=regularizers.l2(5e-4), activity_regularizer=regularizers.l2(1e-5))(X)
    # X = Dropout(dropoutRate, input_shape = (size,))(X)
    # X = Dense(size, activation='relu', kernel_regularizer=regularizers.l1_l2(l1=1e-5, l2=5e-4), bias_regularizer=regularizers.l2(5e-4), activity_regularizer=regularizers.l2(1e-5))(X)
    # X = Dropout(dropoutRate, input_shape = (size,))(X)
    # X = Dense(size, activation='relu', kernel_regularizer=regularizers.l1_l2(l1=1e-5, l2=5e-4), bias_regularizer=regularizers.l2(5e-4), activity_regularizer=regularizers.l2(1e-5))(X)
    # X = Dropout(dropoutRate, input_shape = (size,))(X)
    # X = Dense(size, activation='relu', kernel_regularizer=regularizers.l1_l2(l1=1e-5, l2=5e-4), bias_regularizer=regularizers.l2(5e-4), activity_regularizer=regularizers.l2(1e-5))(X)
    # X = Dropout(dropoutRate, input_shape = (size,))(X)
    #X = BatchNormalization(axis = -1)(X)
    # X = Dense(128*45, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # #X = BatchNormalization(axis = -1)(X)
    # X = Dense(128*45, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    #X = BatchNormalization(axis = -1)(X)
    # X = Dense(128*5, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # #X = BatchNormalization(axis = -1)(X)
    # X = Dense(128*5, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # #X = BatchNormalization(axis = -1)(X)
    # X = Dense(128*5, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    #X = BatchNormalization(axis = -1)(X)
    # X = Dense(128*5, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(128*5, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(128*5, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(128*5, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(128*5, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    #X = BatchNormalization(axis = -1)(X)
    # X = Dense(128*10, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(128*10, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = Dense(128*10, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    #+X = BatchNormalization(axis = -1)(X)
    #X = Dense(64*8, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    #X = BatchNormalization(axis = -1)(X)
    #X = Dense(32, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = BatchNormalization(axis = -1)(X)
    # X = Dense(128, activation='relu', kernel_regularizer=regularizers.l2(1e-9))(X)
    # #X = BatchNormalization(axis = -1)(X)
    # X = Dense(128, activation='relu', kernel_regularizer=regularizers.l2(0.01))(X)
    # # # X = BatchNormalization(axis = -1)(X)
    # # # X = Dense(80, activation='relu')(X)
    # # #X = BatchNormalization(axis = -1)(X)
    # X = Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.01))(X)
    # X = Dense(32, activation='relu', kernel_regularizer=regularizers.l2(0.01))(X)
    # # X = BatchNormalization(axis = -1)(X)
    #X = Dense(16, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # # X = BatchNormalization(axis = -1)(X)
    #X = Dense(8, activation='relu', kernel_regularizer=regularizers.l2(regularizationConst))(X)
    # X = BatchNormalization(axis = -1)(X)
    # X = Dense(30, activation='relu')(X)
   # X = BatchNormalization(axis = -1)(X)
    X = Dense(5, activation="sigmoid")(X)

    # Create model
    model = Model(inputs = X_input, outputs = X, name='deepNN')

    return model
